const RouteName = {
  SPLSH: 'SplashScreen',
  SWIPER_SCREEN: 'Swiperscreen',
  LOGIN_SCREEN: 'LoginScreen',
  REGISTER_SCREEN: 'Register',
  OTP_VERIFY_SCREEN: 'OtpVerifyScreen',
  // HOME_SCREEN: 'HomeScreen',
  SIDE_NAVIGATOR: 'SideNavigator',
  REGIATRAION_SUCCESSFULL: 'RegistrationSuccessful',
  HOME_SCREEN_TAB_ALL:'HomeScsreenTabAll',
  HOME_TAB: 'HomeTab',
  BOOKING_TAB: 'BookingTab',
  HISTORY_TAB: 'HistoryTabss',
  PROFILE_TAB: 'Profiless',
  SELECT_LANGUAGE: 'TranslationScreen',
  FORGOT_PASSWORD: 'ForgotPassword',
  HELP_SCREEN: 'HelpScreen',
  SETTING_SCREEN: 'SettingsScreen',
  FAQ_SCREEN: 'FAQScreen',
  REVIEWS_SCREEN: 'ReviewsScreen',
  NOTIFICTION_SCREEN: 'NotificationScreen',
  BUS_LIST_SCREEN: 'BusListScreen',
  BUS_SEAT_SCREEN: 'BusSeatScreen',
  PAYMENT_SCREEN: 'PaymentScreen',
  CREDIT_CARD_SCREEN: 'CreditCardScreen',
  PAYMENT_SUCCESSFULLY: 'PaymentSuccessFully',
  TRAIN_LIST_SCREEN: 'TrainBookingListScreen',
  FLIGHT_LIST_SCREEN: 'FlightListScreen',
  TICKET_SCREEN: 'TicketScreen',
  BUS_SELECT_SCREEN: 'BusSelectScreen',
  BORDING_DROPING_POINT: 'BoardingDroping',
  PASSANGER_INFORMATION: 'PassengerInformation',
  REVIEW_BOOKING: 'ReviewBooking',
  FLIGHT_DETAILS: 'FlightDetails',
  FLIGHT_TRAVELER_DETAILS: 'FlightTravellerDetails',
  FLIGHT_MEALS: 'FlightMeals',
  FLIGHT_REVIEW_DETAILS: 'FlightReviewDetails',
  HOTEL_LIST_SCREEN: 'HotelListScreen',
  HOTEL_DESCRIPTION_SCREEN: 'HotelDescriptionPage',
  HOTEL_MORE_DETAILS: 'HotelMoreDetails',
  HOTEL_GUEST_DETAILS: 'HotelGuestDetails',
  HOTEL_PAYMENT: 'HotelPayment',
  HOTEL_PAYMENT: 'HotelPayment',
  BUS_TICKET_SCREEN: 'BusTicketScreen',
  FLIGHT_TICKET_SCREEN: 'FlightTicketScreen',
  HOTEL_TICKET_SCREEN: 'HotelTicketScreen',
  REVIEW_FLIGHT_TICKET_SCREEN: 'ReviewFlightTicketStatus',
  REVIEW_BUS_TICKET_SCREEN: 'ReviewBusTicketStatus',
  REVIEW_HOTEL_TICKET_SCREEN: 'ReviewHotelTicketStatus',
  BUS_BOOKING:'BusBooking',
  CUSTOM_NAVIGATOR:'CustomSidebarMenu'
};
export default RouteName;
