import {SH, SF, SW} from '../../utils';
import {StyleSheet} from 'react-native';

export default BusSeatScreenStyle = Colors =>
  StyleSheet.create({
    ButtonStyle: {
      width: '100%',
      borderRadius: SW(10),
      height: 'auto',
      paddingVertical: SH(10),
    },
    Widththree: {
      width: '40%',
      paddingLeft: SH(20),
      paddingRight: SH(5),
    },
    SelectedSeattext: {
      color: Colors.black_text_color,
      fontSize: SF(16),
      textAlign: 'left',
      fontWeight: '800',
    },
    Selectedtext: {
      color: Colors.gray_text_color,
      fontSize: SF(16),
    },
    Widthtwo: {
      width: '20%',
    },
    Widthone: {
      width: '40%',
      paddingLeft: SH(15),
    },
    BusFinalBoookedBox: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: Colors.white_text_color,
      borderTopColor: Colors.black_text_color,
      borderTopWidth: SW(1),
      paddingVertical: SH(5),
    },
    BusSratflatlistbox: {
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: Colors.white_text_color,
      shadowRadius: SW(2),
      shadowOffset: {
        width: SW(0),
        height: SH(-3),
      },
      shadowColor: Colors.shadow_color,
      elevation: 20,
    },
    TabBoxTwo: {
      flexDirection: 'row',
      width: '100%',
      justifyContent: 'space-between',
      marginBottom: SH(10),
    },
    TabBoxTwoMin: {
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: SH(50),
    },
    TabsettextActiveBoxTwo: {
      paddingVertical: SH(5),
      paddingHorizontal: SH(10),
      textAlign: 'center',
      backgroundColor: Colors.blue_color,
      width: '50%',
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
    },
    TabsettextActiveTwo: {
      color: Colors.white_text_color,
      textTransform: 'capitalize',
      fontSize: SF(16),
      textAlign: 'center',
      paddingVertical: SH(3),
      paddingHorizontal: SH(10),
    },
    TableftAciveBorder: {
      borderTopLeftRadius: SW(3),
      borderBottomLeftRadius: SW(3),
    },
    TabsettextBoxTwo: {
      paddingVertical: SH(5),
      paddingHorizontal: SH(10),
      textAlign: 'center',
      width: '50%',
      borderWidth: SW(1),
      borderColor: Colors.black_text_color,
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
    },
    TabsettextTwo: {
      color: Colors.black_text_color,
      textTransform: 'capitalize',
      fontSize: SF(16),
      textAlign: 'center',
      paddingVertical: SH(3),
      paddingHorizontal: SH(10),
    },
    MinFlexView: {
      width: '100%',
      height: '100%',
    },
    SeatAvChildBoxText: {
      color: Colors.black_text_color,
      fontSize: SF(10),
      textAlign: 'center',
    },
    SeatAvChildBox: {
      width: SW(60),
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: SH(5),
    },
    SeatAvlblBox: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: SH(5),
    },
    BuscusionStyle: {
      borderWidth: SW(1),
      borderColor: Colors.black_text_color,
      borderRadius: SW(2),
      width: '100%',
      height: SH(10),
      position: 'absolute',
      bottom: SH(10),
      backgroundColor: Colors.white_text_color,
    },
    BusSeatBox: {
      borderWidth: SW(1),
      borderColor: Colors.black_text_color,
      borderRadius: SW(3),
      justifyContent: 'center',
      alignItems: 'center',
      width: SW(45),
      height: SH(90),
      position: 'relative',
      paddingHorizontal: SH(6),
    },
    BusSeatBoxright: {
      marginRight: SH(40),
    },
    FlexRowSeatLeft: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      alignItems: 'center',
      width: '50%',
    },
    LastListStyle: {
      paddingLeft: SW(10),
    },
    BuscusionStyle: {
      borderWidth: SW(1),
      borderColor: Colors.black_text_color,
      borderRadius: SW(2),
      width: '100%',
      height: SH(10),
      position: 'absolute',
      bottom: SH(10),
      backgroundColor: Colors.white_text_color,
    },
    Width50: {
      width: '50%',
    },
    FlexRowSeatBox: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: SH(40),
      marginBottom: SH(10),
    },
    RchSubheadTextStyle: {
      color: Colors.black_text_color,
      fontSize: SF(15),
      lineHeight: SH(16),
      paddingTop: SH(5),
    },
    CityText: {
      color: Colors.black_text_color,
      fontSize: SF(20),
    },
    CityMainBox: {
      width: '80%',
      paddingLeft: SH(20),
    },
    CityMainBoxWrap: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      width: '80%',
    },
    BackArrowBoxWidthSet: {
      width: '10%',
      justifyContent: 'center',
      alignItems: 'center',
    },
    FlightsCityBox: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      borderBottomColor: Colors.black_text_color,
      borderBottomWidth: SW(0.5),
      paddingVertical: SH(15),
      paddingLeft: SH(10),
    },
  });
