export const Colors = {
  theme_background: '#00b7eb',
  black_text_color: 'black',
  gray_text_color: '#737272',
  light_gray_text_color: '#f2f2f4',
  white_text_color: '#ffffff',
  blue_color: 'blue',
  amber_color: '#FFC000',
  chinese_silver: '#C8C7C8',
  argent_color: '#C2C0C0',
  light_yellow: '#fef7d6',
  wageningen_green: '#299D35',
  shadow_color: '#000',
  green: 'green',
  red_color: 'red',
  purple: 'purple',
  yellow: '#ff9400',
  pink: 'pink',
  light_orange: '#f1c6a9',
  light_green: '#c1e1c5',
  orange: 'orange',
  Rgb_Black: 'rgba(0,0,0,0.25)',
};
export default Colors;
